#!/bin/bash
### BEGIN INIT INFO
# Provides:          CPU Temperature Monitoring
# Required-Start:   
# Required-Stop:    
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Read the CPU temperature and send it to Ganglia
# Description:      
### END INIT INFO

RETVAL=1
prog="cputemp-monitor"

start() {
    echo -n $"Starting $prog: "
    daemon --name=$prog /opt/cputemp-monitor/cputemp-monitor.rb
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && exit 0
    echo "Error starting $prog" 1>&2
}

stop() {
    echo -n $"Stopping $prog: "
    daemon --name=$prog --stop
    RETVAL=$?
}

restart() {
    stop
    sleep 1
    start
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    restart
    ;;
  status)
    cat /var/run/$prog.pid
    RETVAL=$?
    ;;
  *)
    echo $"Usage: $0 {start|stop|status|restart}"
esac

exit $RETVAL
